version: "3"

services:
    app:
        build: .
        command: python flask-api/server.py --prod
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - .:/usr/src/app
